package com.example.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.database.AppInfo;
import com.example.database.TaskEntity;

import com.example.database.AppInfoDao;
import com.example.database.TaskEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig taskEntityDaoConfig;

    private final AppInfoDao appInfoDao;
    private final TaskEntityDao taskEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        taskEntityDaoConfig = daoConfigMap.get(TaskEntityDao.class).clone();
        taskEntityDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        taskEntityDao = new TaskEntityDao(taskEntityDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(TaskEntity.class, taskEntityDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        taskEntityDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public TaskEntityDao getTaskEntityDao() {
        return taskEntityDao;
    }

}
